name: test-deploy-website

on:
  push:
    branches:
      - master
    paths:
      - "website/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --immutable
          yarn add react-day-picker@latest
      - name: Run typecheck (website)
        run: |
          yarn workspace website run typecheck
      - name: Run lint (website)
        run: |
          yarn workspace website run lint --max-warnings 0
      - name: Run test (website)
        run: |
          yarn workspace website run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: |
          yarn install --immutable
          yarn add react-day-picker@latest
      - name: Build website
        run: |
          yarn workspace website build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
